### ISSUE TITLE
Suggestion: Add attribution and an About page

### ISSUE THREAD

**Issue by stevenjmesser** [fryford/corona#8]
Hello!

This looks like a useful dashboard, though it's not easy to understand who created, where the data comes from or which organisation is responsible for it when landing on the page from a shared link. 

Would it be sensible to add a description about the dashboard, its purpose, the publisher and the data sources? There's several dashboards popping up all over the web and new agencies, journalists, fact-checking orgs, etc. will be needing to work out which ones are credible, reliable, trustful, etc. 

(You can double-up on attribution by adding schema.org markup too! Happy to help on that front.)

**Comment by fryford** [comment]
Have partly fix - added a section describing purpose and sources to the page.

Any guidance on schema.org markup welcome

**Comment by stevenjmesser** [comment]
Looks great!
